steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.dotnet', '-t', 'gcr.io/zeni-cloud-core/build-farm/dotnet:8', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/zeni-cloud-core/build-farm/dotnet:8']
images:
  - gcr.io/zeni-cloud-core/build-farm/dotnet:8
options:
  machineType: E2_HIGHCPU_8
timeout: 1800s
