/**
 * zeni create — Scaffold project from official template (Phase 3 P3.2)
 *
 * Usage:
 *   zeni create                          List available templates
 *   zeni create my-app                   Interactive picker
 *   zeni create my-app --template fastapi-rag
 *   zeni create my-app --list            List templates only
 *
 * Pattern lấy cảm hứng:
 *   - npx create-next-app
 *   - npx create-react-app
 *   - npx create-supabase-app
 *
 * Templates registry: ./templates/registry.json
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import { API_BASE } from '../config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REGISTRY_PATH = path.join(__dirname, '..', '..', 'templates', 'registry.json');

function loadRegistry() {
  try {
    return JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf-8'));
  } catch (e) {
    console.error(`\x1b[31m✗\x1b[0m Không load được template registry: ${e.message}`);
    process.exit(1);
  }
}

function listTemplates() {
  const reg = loadRegistry();
  console.log(`\n\x1b[1m\x1b[36mZeni Cloud Starter Templates\x1b[0m  v${reg.version}\n`);
  for (const t of reg.templates) {
    console.log(`  \x1b[1m${t.id.padEnd(28)}\x1b[0m ${t.name}`);
    console.log(`  ${' '.repeat(28)} \x1b[90m${t.description}\x1b[0m`);
    console.log(`  ${' '.repeat(28)} \x1b[33m${t.framework}\x1b[0m · ${t.language}\n`);
  }
  console.log(`Use: \x1b[36mzeni create <name> --template <id>\x1b[0m\n`);
}

function findTemplate(id) {
  const reg = loadRegistry();
  return reg.templates.find(t => t.id === id);
}

function _parseFlags(args) {
  const flags = {};
  const positional = [];
  for (const a of args) {
    if (a.startsWith('--')) {
      const [k, v] = a.slice(2).split('=');
      flags[k] = v ?? true;
    } else {
      positional.push(a);
    }
  }
  return { flags, positional };
}

export async function create(args) {
  const { flags, positional } = _parseFlags(args);

  // No args or --list → list templates
  if (positional.length === 0 || flags.list) {
    return listTemplates();
  }

  const projectName = positional[0];
  const templateId = flags.template || flags.t || 'nextjs-saas';

  // Validate project name (DNS-safe)
  if (!/^[a-z][a-z0-9-]{1,62}$/.test(projectName)) {
    console.error(`\x1b[31m✗\x1b[0m Tên project không hợp lệ: ${projectName}`);
    console.error(`  Phải lowercase, bắt đầu bằng chữ, chỉ a-z 0-9 dấu gạch. Max 63 ký tự.`);
    process.exit(1);
  }

  // Check if folder already exists
  const targetDir = path.resolve(process.cwd(), projectName);
  if (fs.existsSync(targetDir)) {
    console.error(`\x1b[31m✗\x1b[0m Thư mục đã tồn tại: ${targetDir}`);
    process.exit(1);
  }

  // Lookup template
  const tpl = findTemplate(templateId);
  if (!tpl) {
    console.error(`\x1b[31m✗\x1b[0m Template không tồn tại: ${templateId}`);
    console.error(`  Available: ${loadRegistry().templates.map(t => t.id).join(', ')}`);
    process.exit(1);
  }

  console.log(`\n\x1b[36m→\x1b[0m Creating ${projectName} từ template \x1b[1m${tpl.id}\x1b[0m...`);
  console.log(`  Framework: ${tpl.framework}`);
  console.log(`  Source:    ${tpl.git}\n`);

  // Clone template via git (shallow)
  try {
    execSync(
      `git clone --depth=1 --branch=${tpl.branch || 'main'} ${tpl.git} ${projectName}`,
      { stdio: 'inherit' }
    );
  } catch (e) {
    console.error(`\x1b[31m✗\x1b[0m Git clone failed. Verify network + GitHub repo public.`);
    process.exit(1);
  }

  // Remove .git folder (fresh start)
  try {
    fs.rmSync(path.join(targetDir, '.git'), { recursive: true, force: true });
  } catch (e) { /* ignore */ }

  // Write zeni.json with template preset
  const zeniJson = {
    project_name: projectName,
    template: tpl.id,
    framework: tpl.framework,
    ...tpl.preset,
    api_base: API_BASE,
    created_at: new Date().toISOString(),
  };
  fs.writeFileSync(
    path.join(targetDir, 'zeni.json'),
    JSON.stringify(zeniJson, null, 2),
    'utf-8'
  );

  // Friendly README append
  const readmePath = path.join(targetDir, 'README.md');
  const zeniSection = `

---

## 🚀 Deploy với Zeni Cloud

\`\`\`bash
cd ${projectName}
# 1. Login Zeni Cloud (cần PAT từ https://zenicloud.io/app)
zeni login --token zeni_pat_xxx --workspace YOUR_WS

# 2. Set required env vars
${(tpl.env_required || []).map(e => `zeni env set ${e}=...`).join('\n')}

# 3. Deploy
zeni deploy

# 4. (Optional) Map custom domain
zeni domain add app.example.com
\`\`\`

Generated by zeni-cli v0.3.0 · ${tpl.id} template
`;
  try {
    fs.appendFileSync(readmePath, zeniSection, 'utf-8');
  } catch (e) { /* README may not exist — ignore */ }

  console.log(`\n\x1b[32m✓\x1b[0m Project ${projectName} ready!\n`);
  console.log(`Next steps:`);
  console.log(`  \x1b[36mcd ${projectName}\x1b[0m`);
  console.log(`  \x1b[36mzeni login --token <PAT> --workspace <ws>\x1b[0m`);
  if (tpl.env_required && tpl.env_required.length) {
    console.log(`  \x1b[36mzeni env set ${tpl.env_required[0]}=...\x1b[0m  (${tpl.env_required.length} env vars cần set)`);
  }
  console.log(`  \x1b[36mzeni deploy\x1b[0m`);
  console.log(`\nDocs: https://zenicloud.io/docs/templates/${tpl.id}\n`);
}
