/**
 * zeni help — Usage guide
 */
export async function help() {
  console.log(`
\x1b[1mZeni Cloud CLI\x1b[0m  v0.1.0
Deploy apps to https://zenicloud.io from terminal — no GitHub, no Docker required.

\x1b[1mUSAGE\x1b[0m
  zeni <command> [options]

\x1b[1mAUTHENTICATION\x1b[0m
  zeni login                        Login bằng email/password (interactive)
  zeni login --token <PAT> --workspace <id>
                                    Login với Personal Access Token (recommended)
  zeni whoami                       Show current login + verify với backend
  zeni logout                       Clear local config

\x1b[1mPROJECT\x1b[0m
  zeni init                         Auto-detect framework → tạo zeni.json
  zeni deploy                       Zip current dir → upload → build → deploy → URL live
  zeni list (or ls)                 Liệt kê projects trong workspace
  zeni logs <project>               Logs cho project (Cloud Logging viewer)
  zeni open [project]               Open project URL in browser (or dashboard)

\x1b[1mEXAMPLES\x1b[0m
  $ npm install -g @zenicloud/cli
  $ zeni login --token zeni_pat_xxx --workspace makewits
  $ cd /path/to/my-app
  $ zeni init                       # → creates zeni.json
  $ zeni deploy                     # → URL live trong 60-90s
  $ zeni list                       # → see all projects
  $ zeni open my-app                # → open in browser

\x1b[1mZENI.JSON\x1b[0m (auto-generated by 'zeni init')
  {
    "name": "my-app",
    "framework": "nextjs",          // auto | nextjs | react | vue | static | fastapi | express | custom
    "port": 3000,
    "region": "asia-southeast1",
    "size": "s",                    // xs | s | m | l
    "env_vars": { "NODE_ENV": "production" },
    "ignore": ["node_modules", ".git"]
  }

\x1b[1mENV VARS\x1b[0m
  ZENI_TOKEN        Override token from ~/.zeni/config.json
  ZENI_WORKSPACE    Override workspace
  ZENI_API          Override API base (default: https://zenicloud.io/api/v1)
  ZENI_DEBUG        Print stack traces on error

\x1b[1mLINKS\x1b[0m
  Docs:        https://zenicloud.io/docs/cli
  AI Agent:    https://zenicloud.io/docs/ai-agent-deploy.html
  Dashboard:   https://zenicloud.io/app
  Support:     hello@zenicloud.io
`);
}
